import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


terminal SEP, TOK1, TOK2, TOK3;
terminal String QSTRING;
terminal Integer UINT;


//terminal Float FLOAT;
//terminal Double DOUBLE;


non terminal prog;
non terminal header ;
non terminal Integer NT0;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double;
// non terminal Boolean ;


//precedences and associativities
// precedence left OR;
// precedence left AND;
// precedence left NOT;
// precedence left LT, GT, LE, GE, EQ, NEQ;
// precedence left PLUS, MINUS;
// precedence left STAR, DIV;


/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= 
;

// HANDLE IF CONDITIONS, REMEMBER PRECEDENCES
/*
bool_exp ::= TRUE {: RESULT = true; :} | FALSE {: RESULT = false; :} |
            bool_exp:x AND bool_exp:y {: RESULT = x && y; :} |
            bool_exp:x OR bool_exp:y  {: RESULT = x || y; :} |
            NOT bool_exp:x     {: RESULT = !x; :} |
            RO bool_exp:x RC {:RESULT = x; :} |
            VAR:key {:RESULT = new Boolean(parser.table.get(key)); :}
*/
