import java_cup.runtime.*;
import java.util.*;
import java.io.*;


init with{:
    table = new HashMap <String, HashMap <String, Double>>();
:};

parser code {:
    public HashMap <String, HashMap <String, Double>> table;

    public Object stack(int position){
        return (((Symbol)stack.elementAt(tos + position)).value);
    }
:};


terminal SEP, TOK1, TOK2, TOK3;
terminal String QSTRING;
terminal Integer UINT;


//terminal Float FLOAT;
//terminal Double DOUBLE;


non terminal prog;
non terminal header ;
non terminal Integer NT0;
// non terminal String ;
// non terminal HashMap ;
// non terminal Integer ;
// non terminal Double;
// non terminal Boolean ;


//precedences and associativities
// precedence left OR;
// precedence left AND;
// precedence left NOT;
// precedence left LT, GT, LE, GE, EQ, NEQ;
// precedence left PLUS, MINUS;
// precedence left STAR, DIV;


/////////////////////////////
//// Grammar
////////////////////////////

start with prog;

prog ::= 
;

// HANDLE IF CONDITIONS, REMEMBER PRECEDENCES
/*
if_commands ::= IF bool_exp:condition THEN print_list FI
;

bool_exp ::= bool_exp:x AND bool_exp:y {: RESULT = x && y; :} |
              bool_exp:x OR bool_exp:y  {: RESULT = x || y; :} |
              NOT RO bool_exp:x RC       {: RESULT = !x; :} |
              RO bool_exp:x RC          {: RESULT = x; :} |
              QSTRING:house_name DOT QSTRING:room_name EQ UINT:area {:
                  HashMap <String, Integer> house = parser.table.get(house_name);
                  Integer room_area = (Integer) house.get(room_name);
                  if (room_area.equals(area))
                      RESULT = true;
                  else
                      RESULT = false;
              :}
;
*/
